# -*- coding: utf-8 -*-
"""Check if year is leap year_Sketo_26feb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FjM8k8E0TlwIEz3i_91pYE1ZuOaNxsBD
"""

var_year=int(input("Enter the year you want to check --"))
if (var_year%4==0):
  print("the year",var_year,"is leap year")
else:
  print ("the year",var_year,"is NOT a leap year")